# Generated by Django 6.0.7 on 2026-07-30 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tbl_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=50, null=True)),
                ('added_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
                ('category_picture', models.ImageField(null=True, upload_to='static/category/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/software/')),
                ('download_link', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_upcomingbatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('batchname', models.CharField(max_length=100, null=True)),
                ('batch_picture', models.ImageField(null=True, upload_to='static/batch/')),
                ('starting_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_lectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.TextField(null=True)),
                ('video_description', models.TextField(null=True)),
                ('video_link', models.CharField(max_length=200, null=True)),
                ('added_date', models.DateField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbl_category')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('time', models.CharField(max_length=30, null=True)),
                ('date', models.DateField(null=True)),
                ('joining_link', models.TextField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/liveclass/')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbl_batch')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('description', models.TextField(null=True)),
                ('notes_file', models.FileField(null=True, upload_to='static/notes/')),
                ('added_date', models.DateField(null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbl_batch')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('marks', models.IntegerField(null=True)),
                ('task_file', models.FileField(null=True, upload_to='static/task/')),
                ('added_date', models.DateField(null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbl_batch')),
            ],
        ),
    ]
