# Generated by Django 6.0.7 on 2026-07-31 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_tbl_batch_tbl_category_tbl_software_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_category',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.tbl_batch'),
        ),
        migrations.AddField(
            model_name='tbl_register',
            name='user_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.tbl_batch'),
        ),
    ]
